require "active_support/core_ext/integer/time"
require_relative "../health_check_host_authorization"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # In the development environment your application's code is reloaded any time
  # it changes. This slows down response time but is perfect for development
  # since you don't have to restart the web server when you make code changes.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable caching. By default caching is disabled.
  # Run rails dev:cache to toggle caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true

    config.cache_store = :memory_store
    config.public_file_server.headers = { "Cache-Control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false

    config.cache_store = :null_store
  end

  # Store uploaded files using the configured development service.
  config.active_storage.service = ENV.fetch("ACTIVE_STORAGE_SERVICE", "local").to_sym

  config.active_job.queue_adapter = ENV.fetch("ACTIVE_JOB_QUEUE_ADAPTER", "sidekiq").to_sym

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Disable caching for Action Mailer templates even if Action Controller
  # caching is enabled.
  config.action_mailer.perform_caching = false

  config.action_mailer.default_url_options = { host: "localhost", port: ENV.fetch("PORT", 4000) }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise exceptions for disallowed deprecations.
  config.active_support.disallowed_deprecation = :raise

  # Tell Active Support which deprecation messages to disallow.
  config.active_support.disallowed_deprecation_warnings = []

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
  #

  config.action_controller.allow_forgery_protection = false

  config.log_level = :debug

  # Web Console 설정
  config.web_console.allowed_ips = "0.0.0.0/0"

  # Enable DNS rebinding protection and other `Host` header attacks.
  #
  # 기본은 오늘과 동일하게 "localhost:PORT" 하나뿐이다. ALLOWED_HOSTS를 주면(형식은
  # production과 동일 — 쉼표로 구분한 host:port 목록) 그 목록으로 완전히 대체된다.
  # 컨테이너 네트워크에서 서비스명 호스트(예: api:4000)로 불릴 때 Host 헤더가
  # localhost가 아니라서 막히던 Blocked Host를 이렇게 풀 수 있다.
  #
  # 빈 문자열은 "설정 안 함"으로 취급한다(ENV["ALLOWED_HOSTS"].presence). .env.example을
  # 그대로 복사해 ALLOWED_HOSTS=를 빈 채로 둔 기존 로컬 흐름이 config.hosts = []
  # (host 검사 자체가 꺼짐)로 조용히 바뀌면 안 되기 때문이다.
  config.hosts =
    if (allowed_hosts = ENV["ALLOWED_HOSTS"].presence)
      allowed_hosts.split(",")
    else
      [ "localhost:#{ENV.fetch("PORT", 4000)}" ]
    end

  # 컨테이너 헬스체크는 Host 검사에서 제외한다 — production 과 같은 술어를 쓴다.
  #
  # 이것이 없으면 development 스테이지 컨테이너의 HEALTHCHECK 가 localhost 를
  # 겨눌 때 ALLOWED_HOSTS 와 무관하게 403 Blocked hosts 로 항상 막히고,
  # `docker compose up --wait` 가 스택 전체를 실패로 처리한다.
  config.host_authorization = { exclude: HealthCheckHostAuthorization::EXCLUDE }
end
